// src/lib/myBackend.ts

import { IBooks } from "@/interfaces/lib/myBackendInterface";

export const userDB = "admin";
export const passwordDB = "admin";
export const tokenDB = "fake-jwt-token";
export const myCategorys = (): string[] => [
  "Autoayuda",
  "Aventuras",
  "Ciencia ficción",
  "Distopía",
  "Drama",
  "Épica",
  "Experimental",
  "Fábula filosófica",
  "Fantasía",
  "Ficción espiritual",
  "Ficción psicológica",
  "Ficción social",
  "Ficción",
  "Filosofía",
  "Gótico",
  "Histórico",
  "Horror",
  "Justicia social",
  "Literatura antigua",
  "Literatura juvenil",
  "Literatura latinoamericana",
  "Misterio",
  "Novela clásica",
  "Psicología",
  "Realismo mágico",
  "Romance",
  "Terror",
  "Thriller",
]
export const myBackend = (): IBooks[] => {
  return [
    {
      id: 1,
      title: "Cien años de soledad",
      author: "Gabriel García Márquez",
      category: ["Ficción", "Realismo mágico"],
      year: 1967,
      genre: "Realismo mágico",
      pages: 471,
      publisher: "Editorial Sudamericana",
      language: "Español",
      isbn: "9780307474728",
      tags: ["clásico", "realismo mágico", "literatura latinoamericana"],
      description:
        "La historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.",
      price: 25,
     image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0CJJuTOkHjM5qsix_d4wVR_szL9weNLWVJA&s",

    },
    {
      id: 2,
      title: "Don Quijote de la Mancha",
      author: "Miguel de Cervantes",
      category: ["Novela clásica", "Aventuras", "Ficción"],
      year: 1605,
      genre: "Novela clásica",
      pages: 863,
      publisher: "Francisco de Robles",
      language: "Español",
      isbn: "9788491050297",
      tags: ["clásico", "aventuras", "literatura española"],
      description:
        "Las aventuras del ingenioso hidalgo Don Quijote y su escudero Sancho Panza en su búsqueda de justicia.",
      price: 30,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/73/b6/73b6fd96c31d26e2b6a3531808c1188c.jpg",
    },
    {
      id: 3,
      title: "1984",
      author: "George Orwell",
      category: ["Distopía", "Ciencia ficción", "Ficción"],
      year: 1949,
      genre: "Distopía",
      pages: 328,
      publisher: "Secker & Warburg",
      language: "Inglés",
      isbn: "9780451524935",
      tags: ["distopía", "ciencia ficción", "política"],
      description:
        "Una crítica al totalitarismo y la vigilancia estatal a través del régimen del Gran Hermano.",
      price: 20,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/10/42/10426f9e9ae4f7cd9eb5d33cef5aa143.jpg"
    },
    {
      id: 4,
      title: "El Principito",
      author: "Antoine de Saint-Exupéry",
      category: ["Fábula filosófica", "Filosofía", "Ficción"],
      year: 1943,
      genre: "Fábula filosófica",
      pages: 96,
      publisher: "Reynal & Hitchcock",
      language: "Francés",
      tags: ["infantil", "filosofía", "clásico"],
      isbn: "9780156012195",
      description:
        "Un cuento sobre la inocencia, la amistad y el amor contado desde la perspectiva de un niño viajero.",
      price: 15,
      image: "https://image.cdn1.buscalibre.com/5b57fc1690f0b5295a8b4567.__RS360x360__.jpg"
    },
    {
      id: 5,
      title: "Crimen y castigo",
      author: "Fiódor Dostoyevski",
      category: ["Ficción psicológica", "Psicología", "Ficción"],
      year: 1866,
      genre: "Ficción psicológica",
      pages: 671,
      publisher: "The Russian Messenger",
      language: "Ruso",
      tags: ["clásico", "psicología", "filosofía"],
      isbn: "9780140449136",
      description:
        "Raskólnikov lucha con la culpa y la redención tras cometer un asesinato en San Petersburgo.",
      price: 27,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/ea/1f/ea1fc691874fa49ce341d876a981e2c1.jpg"
    },
    {
      id: 6,
      title: "Orgullo y prejuicio",
      author: "Jane Austen",
      category: ["Romance", "Novela clásica", "Ficción"],
      year: 1813,
      genre: "Romance clásico",
      pages: 279,
      publisher: "T. Egerton",
      language: "Inglés",
      isbn: "9781503290563",
      tags: ["romance", "clásico", "literatura inglesa"],
      description:
        "La historia de Elizabeth Bennet y el señor Darcy en una crítica social sobre la época georgiana.",
      price: 19,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/60/b3/60b3e7711e26b916eb87d493d544f3a3.jpg"
    },
    {
      id: 7,
      title: "Matar a un ruiseñor",
      author: "Harper Lee",
      category: ["Ficción social", "Justicia social", "Ficción"],
      year: 1960,
      genre: "Ficción social",
      pages: 281,
      publisher: "J.B. Lippincott & Co.",
      language: "Inglés",
      tags: ["clásico", "justicia social", "literatura estadounidense"],
      isbn: "9780061120084",
      description:
        "Una niña narra la lucha de su padre, un abogado, por defender a un hombre negro injustamente acusado.",
      price: 22,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/1b/d7/1bd7b432c94ccdcf816c917d8abe8e83.jpg"
    },
    {
      id: 8,
      title: "El nombre de la rosa",
      author: "Umberto Eco",
      category: ["Misterio", "Histórico", "Ficción"],
      year: 1980,
      genre: "Misterio histórico",
      pages: 512,
      publisher: "Bompiani",
      language: "Italiano",
      tags: ["misterio", "histórico", "literatura italiana"],
      isbn: "9780156001311",
      description:
        "Un fraile franciscano investiga una serie de asesinatos en una abadía medieval.",
      price: 24,
      image: "https://librerialerner.vtexassets.com/arquivos/ids/1887005/principal.gif?v=638625404284000000"
    },
    {
      id: 9,
      title: "El Hobbit",
      author: "J. R. R. Tolkien",
      category: ["Fantasía", "Aventuras", "Ficción"],
      year: 1937,
      genre: "Fantasía",
      pages: 310,
      publisher: "George Allen & Unwin",
      language: "Inglés",
      tags: ["fantasía", "aventura", "literatura inglesa"],
      isbn: "9780547928227",
      description:
        "Bilbo Bolsón emprende una aventura inesperada junto a enanos para recuperar un tesoro custodiado por un dragón.",
      price: 23,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/41/6e/416eeb7550b8e2c7ef26aecaa2af460b.jpg"
    },
    {
      id: 10,
      title: "Los miserables",
      author: "Victor Hugo",
      category: ["Drama", "Histórico", "Ficción"],
      year: 1862,
      genre: "Drama histórico",
      pages: 1232,
      publisher: "A. Lacroix, Verboeckhoven & Cie.",
      language: "Francés",
      tags: ["clásico", "drama", "literatura francesa"],
      isbn: "9780451419439",
      description:
        "Jean Valjean busca redención mientras es perseguido por el implacable inspector Javert.",
      price: 33,
      image: "https://www.anayainfantilyjuvenil.com/images/libros/grande/9788469866405-los-miserables-clasicos-a-medida.jpg"
    },
    {
      id: 11,
      title: "Rayuela",
      author: "Julio Cortázar",
      category: ["Experimental", "Literatura latinoamericana", "Ficción"],
      year: 1963,
      genre: "Experimental",
      pages: 600,
      publisher: "Editorial Sudamericana",
      language: "Español",
      tags: ["experimental", "literatura latinoamericana", "clásico"],
      isbn: "9788437604185",
      description:
        "Una novela abierta que invita al lector a decidir el orden de lectura y a reflexionar sobre la existencia.",
      price: 26,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/90/53/905322d10841b36aa311dbd5c90d92ed.jpg"
    },
    {
      id: 12,
      title: "Fahrenheit 451",
      author: "Ray Bradbury",
      category: ["Ciencia ficción", "Distopía", "Ficción"],
      year: 1953,
      genre: "Ciencia ficción",
      pages: 194,
      publisher: "Ballantine Books",
      language: "Inglés",
      isbn: "9781451673319",
      tags: ["distopía", "ciencia ficción", "clásico"],
      description:
        "Una sociedad futurista donde los libros están prohibidos y los bomberos los queman.",
      price: 20,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/23/e3/23e3b0699ae46fc450e85f4354328c3a.jpg"
    },
    {
      id: 13,
      title: "La sombra del viento",
      author: "Carlos Ruiz Zafón",
      category: ["Misterio", "Ficción"],
      year: 2001,
      genre: "Misterio literario",
      pages: 565,
      publisher: "Planeta",
      language: "Español",
      tags: ["misterio", "literatura española", "bestseller"],
      isbn: "9788408172177",
      description:
        "Un joven descubre un libro maldito que cambia su vida en la Barcelona de la posguerra.",
      price: 28,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/97/a9/97a9e0ef37c3b33e9303147883d03372.jpg"
    },
    {
      id: 14,
      title: "It",
      author: "Stephen King",
      category: ["Terror", "Horror", "Ficción"],
      year: 1986,
      genre: "Terror",
      pages: 1138,
      publisher: "Viking Press",
      language: "Inglés",
      tags: ["terror", "horror", "literatura estadounidense"],
      isbn: "9780450411433",
      description:
        "Un grupo de amigos enfrenta a una entidad maligna que toma la forma de un payaso llamado Pennywise.",
      price: 29,
      image: "https://i.redd.it/it-book-cover-v0-helamqh24s9f1.jpg?width=1600&format=pjpg&auto=webp&s=f072267b33abd9f638f7461974d61fdb9df69d1c"
    },
    {
      id: 15,
      title: "El alquimista",
      author: "Paulo Coelho",
      category: ["Ficción espiritual", "Autoayuda", "Ficción"],
      year: 1988,
      genre: "Ficción espiritual",
      pages: 208,
      publisher: "HarperOne",
      tags: ["espiritualidad", "autoayuda", "bestseller"],
      language: "Portugués",
      isbn: "9780061122415",
      description:
        "Santiago, un joven pastor, emprende un viaje en busca de su leyenda personal y del verdadero tesoro de la vida.",
      price: 17,
      image: "https://www.planetadelibros.com.co/usuaris/libros/fotos/402/original/401512_portada_el-alquimista_barry-kitson_202404031526.jpg"
    },
    {
      id: 16,
      title: "Los juegos del hambre",
      author: "Suzanne Collins",
      category: ["Ciencia ficción", "Distopía", "Literatura juvenil"],
      year: 2008,
      genre: "Ciencia ficción distópica",
      pages: 374,
      publisher: "Scholastic Press",
      language: "Inglés",
      isbn: "9780439023481",
      tags: ["distopía", "aventura", "literatura juvenil"],
      description:
        "Katniss Everdeen debe sobrevivir a un mortal torneo televisado donde solo uno puede quedar con vida.",
      price: 19,
      image:"https://images.cdn3.buscalibre.com/fit-in/360x360/0b/33/0b33dc8290d82650f4ace5fb92a4f9aa.jpg"
    },
    {
      id: 17,
      title: "El código Da Vinci",
      author: "Dan Brown",
      category: ["Thriller", "Misterio", "Ficción"],
      year: 2003,
      genre: "Thriller",
      pages: 689,
      publisher: "Doubleday",
      language: "Inglés",
      isbn: "9780307474278",
      tags: ["thriller", "misterio", "bestseller"],
      description:
        "El profesor Langdon descubre una conspiración relacionada con el Santo Grial y sociedades secretas.",
      price: 25,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/b2/ea/b2ea9b952f3b468a2ff88058bd9e3575.jpg"
    },
    {
      id: 18,
      title: "La Odisea",
      author: "Homero",
      category: ["Épica", "Literatura antigua", "Aventuras"],
      year: -800,
      genre: "Épica",
      pages: 541,
      publisher: "Antiguo Grecia",
      language: "Griego",
      isbn: "9780140268867",
      tags: ["clásico", "épica", "literatura antigua"],
      description:
        "Las aventuras de Ulises al intentar regresar a Ítaca tras la guerra de Troya.",
      price: 22,
      image: "https://www.loqueleo.com/do/uploads/2021/08/resized/600_portada-la-odisea.jpg",
    },
    {
      id: 19,
      title: "Drácula",
      author: "Bram Stoker",
      category: ["Terror", "Gótico", "Horror"],
      year: 1897,
      genre: "Terror gótico",
      pages: 418,
      publisher: "Archibald Constable and Company",
      language: "Inglés",
      isbn: "9780486411095",
      tags: ["terror", "gótico", "clásico"],
      description:
        "El conde Drácula intenta trasladarse a Inglaterra mientras un grupo de personas intenta detenerlo.",
      price: 18,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/76/dc/76dc4380329a0f6f3d38ae712e5407ac.jpg",
    },
    {
      id: 20,
      title: "El señor de los anillos: La comunidad del anillo",
      author: "J. R. R. Tolkien",
      category: ["Fantasía", "Épica", "Aventuras"],
      year: 1954,
      genre: "Fantasía épica",
      pages: 423,
      publisher: "George Allen & Unwin",
      language: "Inglés",
      isbn: "9780261102354",
      tags: ["fantasía", "épica", "literatura inglesa"],
      description:
        "Frodo emprende una misión para destruir el Anillo Único y evitar que caiga en manos del mal.",
      price: 35,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/88/13/8813e98d85a1ec7cdae072c6d74a85b2.jpg"
    },

{
      id: 21,
      title: "La casa de los espíritus",
      author: "Isabel Allende",
      category: ["Realismo mágico", "Ficción", "Literatura latinoamericana"],
      year: 1982,
      genre: "Realismo mágico",
      pages: 448,
      publisher: "Plaza & Janés",
      language: "Español",
      isbn: "9788408053759",
      tags: ["clásico", "realismo mágico", "Chile"],
      description:
        "Saga familiar donde lo sobrenatural y lo político se entrelazan en varias generaciones.",
      price: 24,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/bf/30/bf3012b29b7a91ec9442ae13e90d7b4c.jpg"
    },
    {
      id: 22,
      title: "La insoportable levedad del ser",
      author: "Milan Kundera",
      category: ["Filosofía", "Drama", "Ficción"],
      year: 1984,
      genre: "Drama filosófico",
      pages: 314,
      publisher: "Harper & Row",
      language: "Checo",
      isbn: "9780060932138",
      tags: ["filosofía", "existencialismo", "clásico moderno"],
      description:
        "Una reflexión sobre el amor, la libertad y el peso de las decisiones durante la Primavera de Praga.",
      price: 21,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/12/ef/12ef4b408a941a1cc37171bd3c70bf3f.jpg"
    },
    {
      id: 23,
      title: "La ladrona de libros",
      author: "Markus Zusak",
      category: ["Histórico", "Drama", "Ficción"],
      year: 2005,
      genre: "Drama histórico",
      pages: 552,
      publisher: "Picador",
      language: "Inglés",
      isbn: "9780375842207",
      tags: ["histórico", "Segunda Guerra Mundial", "bestseller"],
      description:
        "Una niña encuentra refugio en los libros mientras el mundo a su alrededor se desmorona.",
      price: 23,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYCSVae4s7D0EG8HbqvQZj9lt9GeWjgHoM7A&s"
    },
    {
      id: 24,
      title: "Neuromancer",
      author: "William Gibson",
      category: ["Ciencia ficción", "Cyberpunk", "Ficción"],
      year: 1984,
      genre: "Cyberpunk",
      pages: 271,
      publisher: "Ace Books",
      language: "Inglés",
      isbn: "9780441569595",
      tags: ["cyberpunk", "tecnología", "clásico de ciencia ficción"],
      description:
        "Un hacker fracasado es reclutado para una última misión que redefine la frontera entre humanos y máquinas.",
      price: 18,
      image: "https://www.ccyberdark.net/wp-content/uploads/2021/05/Neuromancer.jpeg"
    },
    {
      id: 25,
      title: "El amor en los tiempos del cólera",
      author: "Gabriel García Márquez",
      category: ["Romance", "Realismo mágico", "Ficción"],
      year: 1985,
      genre: "Romance literario",
      pages: 368,
      publisher: "Oveja Negra",
      language: "Español",
      isbn: "9780307389732",
      tags: ["romance", "literatura latinoamericana", "clásico"],
      description:
        "Dos amantes esperan décadas para reencontrarse y vivir un amor aplazado por toda una vida.",
      price: 24,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/b0/f6/b0f63d2e281c266b3a13f0cc0162e98b.jpg"
    },
    {
      id: 26,
      title: "Siddhartha",
      author: "Hermann Hesse",
      category: ["Filosofía", "Espiritualidad", "Ficción"],
      year: 1922,
      genre: "Ficción espiritual",
      pages: 160,
      publisher: "New Directions",
      language: "Alemán",
      isbn: "9780811200684",
      tags: ["budismo", "filosofía", "clásico"],
      description:
        "Un joven emprende un viaje espiritual en busca del sentido de la existencia.",
      price: 14,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/b7/85/b785119a93d5e15d7ad5e3e138606417.jpg"
    },
    {
      id: 27,
      title: "La carretera",
      author: "Cormac McCarthy",
      category: ["Distopía", "Drama", "Ficción"],
      year: 2006,
      genre: "Distopía dramática",
      pages: 287,
      publisher: "Alfred A. Knopf",
      language: "Inglés",
      isbn: "9780307387899",
      tags: ["distopía", "supervivencia", "drama"],
      description:
        "Un padre y su hijo cruzan un mundo postapocalíptico aferrándose a la esperanza.",
      price: 19,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/4a/ed/4aedcccd7a54a8010d12c33c3dcf5693.jpg"
    },
    {
      id: 28,
      title: "El perfume",
      author: "Patrick Süskind",
      category: ["Thriller", "Histórico", "Ficción"],
      year: 1985,
      genre: "Thriller histórico",
      pages: 255,
      publisher: "Diogenes Verlag",
      language: "Alemán",
      isbn: "9780140120837",
      tags: ["thriller", "histórico", "psicológico"],
      description:
        "Un hombre con un sentido del olfato extraordinario busca crear la esencia perfecta.",
      price: 20,
      image: "https://cdn.culturagenial.com/es/imagenes/perfume-cke.jpg?class=article"
    },
    {
      id: 29,
      title: "El retrato de Dorian Gray",
      author: "Oscar Wilde",
      category: ["Clásico", "Filosófico", "Ficción"],
      year: 1890,
      genre: "Filosofía gótica",
      pages: 254,
      publisher: "Lippincott's Monthly Magazine",
      language: "Inglés",
      isbn: "9780141439570",
      tags: ["clásico", "filosofía", "gótico"],
      description:
        "Un joven vende su alma por la eterna juventud mientras su retrato revela su verdadera corrupción.",
      price: 16,
      image: "https://www.penguinlibros.com/co/6774473-large_default/el-retrato-de-dorian-gray-los-mejores-clasicos.webp"
    },
    {
      id: 30,
      title: "El psicoanalista",
      author: "John Katzenbach",
      category: ["Thriller", "Suspenso", "Ficción"],
      year: 2002,
      genre: "Thriller psicológico",
      pages: 528,
      publisher: "Ballantine Books",
      language: "Inglés",
      isbn: "9780345426277",
      tags: ["suspenso", "thriller", "psicológico"],
      description:
        "Un terapeuta es amenazado por un misterioso enemigo que lo obliga a descifrar un rompecabezas mortal.",
      price: 22,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/42/e3/42e3e26ee9f47cdafd49928009971990.jpg"
    },
    {
      id: 31,
      title: "El viejo y el mar",
      author: "Ernest Hemingway",
      category: ["Clásico", "Aventura", "Ficción"],
      year: 1952,
      genre: "Aventura literaria",
      pages: 127,
      publisher: "Charles Scribner's Sons",
      language: "Inglés",
      isbn: "9780684801223",
      tags: ["aventura", "clásico", "pesca"],
      description:
        "Un pescador lucha contra un gigantesco pez y contra su propia resistencia en el mar.",
      price: 14,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/e8/5b/e85b3df2fa6464f31299965619563eb0.jpg"
    },
    {
      id: 32,
      title: "Las uvas de la ira",
      author: "John Steinbeck",
      category: ["Drama", "Histórico", "Ficción"],
      year: 1939,
      genre: "Drama social",
      pages: 464,
      publisher: "The Viking Press",
      language: "Inglés",
      isbn: "9780143039433",
      tags: ["histórico", "crítica social", "clásico"],
      description:
        "Una familia lucha por sobrevivir durante la Gran Depresión en busca de una vida digna.",
      price: 22,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/cc/6f/cc6f7def05225c03b5010fbd7893a71e.jpg"
    },
    {
      id: 33,
      title: "El guardián entre el centeno",
      author: "J. D. Salinger",
      category: ["Ficción", "Juvenil", "Clásico"],
      year: 1951,
      genre: "Ficción adolescente",
      pages: 277,
      publisher: "Little, Brown and Company",
      language: "Inglés",
      isbn: "9780316769488",
      tags: ["juventud", "clásico", "existencialismo"],
      description:
        "Un joven narra sus días de confusión, rebeldía y búsqueda de identidad en Nueva York.",
      price: 18,
      image: "https://cdn.culturagenial.com/es/imagenes/el-guardian-entre-el-centeno.jpg?class=article"
    },
    {
      id: 34,
      title: "El silencio de los corderos",
      author: "Thomas Harris",
      category: ["Thriller", "Policial", "Suspenso"],
      year: 1988,
      genre: "Suspenso criminal",
      pages: 352,
      publisher: "St. Martin's Press",
      language: "Inglés",
      isbn: "9780312924584",
      tags: ["thriller", "policial", "psicológico"],
      description:
        "Una joven agente del FBI acude a un brillante asesino para capturar a otro criminal.",
      price: 20,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/11/7a/117a1d3904bcf7ba058a6f60195bb495.jpg"
    },
    {
      id: 35,
      title: "El hombre invisible",
      author: "H. G. Wells",
      category: ["Ciencia ficción", "Clásico", "Ficción"],
      year: 1897,
      genre: "Ciencia ficción",
      pages: 192,
      publisher: "Pearson",
      language: "Inglés",
      isbn: "9780451528529",
      tags: ["ciencia ficción", "clásico", "experimentos"],
      description:
        "Un científico logra volverse invisible, con consecuencias fuera de su control.",
      price: 17,
      image: "https://www.tornamesa.co/imagenes/9788419/978841959908.GIF"
    },
    {
      id: 36,
      title: "La chica del tren",
      author: "Paula Hawkins",
      category: ["Thriller", "Suspenso", "Ficción"],
      year: 2015,
      genre: "Thriller psicológico",
      pages: 395,
      publisher: "Riverhead Books",
      language: "Inglés",
      isbn: "9781594634024",
      tags: ["thriller", "misterio", "bestseller"],
      description:
        "Una mujer presencia algo inquietante desde un tren y se ve envuelta en un caso criminal.",
      price: 21,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/a9/dd/a9dd9755bde59005eb4421bb1f061bcc.jpg"
    },
    {
      id: 37,
      title: "Ready Player One",
      author: "Ernest Cline",
      category: ["Ciencia ficción", "Aventura", "Ficción"],
      year: 2011,
      genre: "Ciencia ficción futurista",
      pages: 374,
      publisher: "Crown Publishing",
      language: "Inglés",
      isbn: "9780307887443",
      tags: ["videojuegos", "futuro", "aventura"],
      description:
        "Un joven compite en un mundo virtual lleno de acertijos para obtener una fortuna.",
      price: 19,
      image: "https://miro.medium.com/v2/resize:fit:1400/1*rmSAlvrcvZqTlg161SCq0Q.jpeg"
    },
    {
      id: 38,
      title: "El cuento de la criada",
      author: "Margaret Atwood",
      category: ["Distopía", "Feminismo", "Ficción"],
      year: 1985,
      genre: "Distopía social",
      pages: 311,
      publisher: "McClelland & Stewart",
      language: "Inglés",
      isbn: "9780385490818",
      tags: ["distopía", "feminismo", "crítica social"],
      description:
        "En un régimen totalitario, las mujeres fértiles son obligadas a servir como reproductoras.",
      price: 22,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/f3/c9/f3c9b4e6308b7efefb72681b646294a0.jpg"
    },
    {
      id: 39,
      title: "Metro 2033",
      author: "Dmitry Glukhovsky",
      category: ["Ciencia ficción", "Postapocalíptico", "Ficción"],
      year: 2002,
      genre: "Postapocalíptico",
      pages: 458,
      publisher: "Eksmo",
      language: "Ruso",
      isbn: "9780575086258",
      tags: ["postapocalíptico", "supervivencia", "ciencia ficción"],
      description:
        "En los túneles del metro de Moscú, los supervivientes luchan contra monstruos y facciones rivales.",
      price: 23,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/27/78/277874092cc48fa66180c2d695082a80.jpg"
    },
    {
      id: 40,
      title: "La elegancia del erizo",
      author: "Muriel Barbery",
      category: ["Filosofía", "Contemporáneo", "Ficción"],
      year: 2006,
      genre: "Ficción filosófica",
      pages: 325,
      publisher: "Gallimard",
      language: "Francés",
      isbn: "9782070780938",
      tags: ["filosofía", "contemporáneo", "reflexión"],
      description:
        "Una portera y una niña genio ocultan su mundo intelectual mientras cuestionan la vida cotidiana.",
      price: 20,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/ce/ee/ceee3e0139fb28fabed0ef2f954da249.jpg"
    },

{
      id: 41,
      title: "La montaña mágica",
      author: "Thomas Mann",
      category: ["Clásico", "Filosofía", "Ficción"],
      year: 1924,
      genre: "Ficción filosófica",
      pages: 720,
      publisher: "S. Fischer Verlag",
      language: "Alemán",
      isbn: "9783596294312",
      tags: ["clásico", "filosofía", "literatura alemana"],
      description:
        "Hans Castorp descubre un mundo introspectivo en un sanatorio alpino donde el tiempo parece detenerse.",
      price: 28,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/75/56/7556ee308c4a24d1a4ea1be13b9ee928.jpg"
    },
    {
      id: 42,
      title: "El ruido y la furia",
      author: "William Faulkner",
      category: ["Moderna", "Ficción psicológica", "Ficción"],
      year: 1929,
      genre: "Modernismo",
      pages: 326,
      publisher: "Jonathan Cape",
      language: "Inglés",
      isbn: "9780679732242",
      tags: ["modernismo", "psicológico", "clásico estadounidense"],
      description:
        "La decadencia de la familia Compson contada a través de múltiples voces y perspectivas.",
      price: 21,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyVg6uN4VZyF35L62NXzK7h_VG04lOgGp-OA&s"
    },
    {
      id: 43,
      title: "El hombre que calculaba",
      author: "Malba Tahan",
      category: ["Matemáticas", "Aventura", "Ficción"],
      year: 1938,
      genre: "Ficción matemática",
      pages: 256,
      publisher: "Record",
      language: "Portugués",
      isbn: "9788532511010",
      tags: ["matemáticas", "aventura", "clásico"],
      description:
        "Las aventuras de un viajero que resuelve enigmas matemáticos con ingenio y creatividad.",
      price: 17,
      image: "https://imagessl7.casadellibro.com/a/l/s5/77/9788498670677.webp"
    },
    {
      id: 44,
      title: "La noche de los tiempos",
      author: "Antonio Muñoz Molina",
      category: ["Histórico", "Drama", "Ficción"],
      year: 2009,
      genre: "Drama histórico",
      pages: 1024,
      publisher: "Seix Barral",
      language: "Español",
      isbn: "9788432213672",
      tags: ["histórico", "Guerra Civil Española", "drama"],
      description:
        "La vida de un arquitecto atrapado entre tensiones políticas y amores imposibles antes de la Guerra Civil Española.",
      price: 30,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/04/04/0404c94cac84ab884c752bb17c3e54fc.jpg"
    },

{
      id: 45,
      title: "La tregua",
      author: "Mario Benedetti",
      category: ["Romance", "Contemporáneo", "Ficción"],
      year: 1960,
      genre: "Romance contemporáneo",
      pages: 208,
      publisher: "Alfaguara",
      language: "Español",
      isbn: "9788420471839",
      tags: ["romance", "latinoamérica", "diario"],
      description:
        "Un oficinista viudo encuentra inesperadamente la posibilidad del amor en su rutinaria vida.",
      price: 16,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/1d/f4/1df4038c647fdb8272795f535b40ce08.jpg"
    },
    {
      id: 46,
      title: "Colmillo Blanco",
      author: "Jack London",
      category: ["Aventura", "Naturaleza", "Ficción"],
      year: 1906,
      genre: "Aventura",
      pages: 298,
      publisher: "Macmillan",
      language: "Inglés",
      isbn: "9780451531345",
      tags: ["aventura", "naturaleza", "clásico"],
      description:
        "La vida de un lobo domesticado que lucha por sobrevivir entre la dureza de la naturaleza y la crueldad humana.",
      price: 15,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM8quBeXrMrOQtdmaA8TV4PLsfACD8J3Dmgw&s"

    },
    {
      id: 47,
      title: "Los pilares de la tierra",
      author: "Ken Follett",
      category: ["Histórico", "Aventura", "Ficción"],
      year: 1989,
      genre: "Ficción histórica",
      pages: 1104,
      publisher: "Macmillan",
      language: "Inglés",
      isbn: "9780451166890",
      tags: ["histórico", "catedrales", "bestseller"],
      description:
        "Una épica historia sobre la construcción de una catedral en la Inglaterra medieval.",
      price: 32,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS47kYVeVuMfPxxrkgPyou3wFpsosvKhi4MwA&s"
    },
    {
      id: 48,
      title: "Tokio Blues",
      author: "Haruki Murakami",
      category: ["Drama", "Contemporáneo", "Ficción"],
      year: 1987,
      genre: "Drama contemporáneo",
      pages: 296,
      publisher: "Kodansha",
      language: "Japonés",
      isbn: "9780375704024",
      tags: ["drama", "amor", "literatura japonesa"],
      description:
        "Un hombre recuerda su juventud marcada por el amor, la pérdida y la fragilidad emocional.",
      price: 19,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/a6/75/a6752f915dc42e51a82057c2224566e4.jpg"
    },
    {
      id: 49,
      title: "El extranjero",
      author: "Albert Camus",
      category: ["Filosofía", "Existencialismo", "Ficción"],
      year: 1942,
      genre: "Existencialismo",
      pages: 123,
      publisher: "Gallimard",
      language: "Francés",
      isbn: "9780679720201",
      tags: ["existencialismo", "clásico", "filosofía"],
      description:
        "Meursault enfrenta las consecuencias de su indiferencia ante el mundo y los acontecimientos.",
      price: 14,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/0d/24/0d24d29aed197876e4ce72ac016818dc.jpg"
    },
    {
      id: 50,
      title: "El gran Gatsby",
      author: "F. Scott Fitzgerald",
      category: ["Clásico", "Drama", "Ficción"],
      year: 1925,
      genre: "Drama moderno",
      pages: 180,
      publisher: "Charles Scribner's Sons",
      language: "Inglés",
      isbn: "9780743273565",
      tags: ["años 20", "clásico", "crítica social"],
      description:
        "La trágica historia de un millonario obsesionado con recuperar un amor perdido.",
      price: 18,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/33/c2/33c26accef7bc42dc170cdea96da543b.jpg"
    },
    {
      id: 51,
      title: "El castillo",
      author: "Franz Kafka",
      category: ["Filosofía", "Surrealismo", "Ficción"],
      year: 1926,
      genre: "Surrealismo",
      pages: 352,
      publisher: "Die Schmiede",
      language: "Alemán",
      isbn: "9780805211061",
      tags: ["surrealismo", "absurdo", "clásico"],
      description:
        "Un agrimensor lucha por obtener acceso a un misterioso castillo cuyos funcionarios son inalcanzables.",
      price: 19,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/82/3a/823a642b582bfe1bcf78b5e1107d4ba6.jpg"
    },
    {
      id: 52,
      title: "El jardín secreto",
      author: "Frances Hodgson Burnett",
      category: ["Infantil", "Clásico", "Aventura"],
      year: 1911,
      genre: "Literatura infantil",
      pages: 331,
      publisher: "Frederick A. Stokes",
      language: "Inglés",
      isbn: "9780064401883",
      tags: ["infantil", "amistad", "clásico"],
      description:
        "Una niña descubre un jardín oculto que transforma su vida y la de quienes la rodean.",
      price: 14,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/04/10/0410be3dff53a4285f6e71968869f160.jpg"
    },
    {
      id: 53,
      title: "Las crónicas de Narnia: El león, la bruja y el ropero",
      author: "C. S. Lewis",
      category: ["Fantasía", "Infantil", "Aventura"],
      year: 1950,
      genre: "Fantasía",
      pages: 208,
      publisher: "Geoffrey Bles",
      language: "Inglés",
      isbn: "9780064404990",
      tags: ["fantasía", "infantil", "clásico"],
      description:
        "Cuatro hermanos descubren un mundo mágico gobernado por criaturas fantásticas y un malvado invierno eterno.",
      price: 17,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/a6/41/a641e8ed5d48d1bf117adf1a374ce82a.jpg"
    },
    {
      id: 54,
      title: "El médico",
      author: "Noah Gordon",
      category: ["Histórico", "Aventura", "Ficción"],
      year: 1986,
      genre: "Ficción histórica",
      pages: 624,
      publisher: "Simon & Schuster",
      language: "Inglés",
      isbn: "9780671624940",
      tags: ["histórico", "medicina", "aventura"],
      description:
        "Un joven inglés viaja al mundo islámico medieval para convertirse en médico.",
      price: 25,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/24/0b/240b0caebb7151e284a037d6ff62ba23.jpg"
    },
    {
      id: 55,
      title: "La chica que soñaba con una cerilla y un bidón de gasolina",
      author: "Stieg Larsson",
      category: ["Thriller", "Policial", "Ficción"],
      year: 2006,
      genre: "Thriller",
      pages: 630,
      publisher: "Norstedts Förlag",
      language: "Sueco",
      isbn: "9780307269980",
      tags: ["thriller", "policial", "bestseller"],
      description:
        "Lisbeth Salander se enfrenta a una oscura red de corrupción mientras su vida vuelve a estar en peligro.",
      price: 26,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQTAz-Z4bFsDM3KWr2FdT_JPZSMEAAa0aDqA&s"
    },
    {
      id: 56,
      title: "Los hombres que no amaban a las mujeres",
      author: "Stieg Larsson",
      category: ["Thriller", "Policial", "Ficción"],
      year: 2005,
      genre: "Thriller",
      pages: 672,
      publisher: "Norstedts Förlag",
      language: "Sueco",
      isbn: "9780307454546",
      tags: ["misterio", "investigación", "bestseller"],
      description:
        "Un periodista y una hacker investigan la desaparición de una mujer ocurrida décadas atrás.",
      price: 25,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/85/0d/850d0196b30b19ad901ca20022a0f2bf.jpg"
    },
    {
      id: 57,
      title: "Trilogía de Nueva York",
      author: "Paul Auster",
      category: ["Misterio", "Metaficción", "Ficción"],
      year: 1985,
      genre: "Metaficción detectivesca",
      pages: 480,
      publisher: "Sun & Moon Press",
      language: "Inglés",
      isbn: "9780140131550",
      tags: ["metaficción", "detectivesco", "contemporáneo"],
      description:
        "Tres historias entrelazadas que juegan con la identidad, el lenguaje y la realidad.",
      price: 23,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/3b/0d/3b0d17a41de97637c3fdc33aaf2bef87.jpg"
    },
    {
      id: 58,
      title: "El jugador",
      author: "Fiódor Dostoyevski",
      category: ["Psicológica", "Clásico", "Ficción"],
      year: 1866,
      genre: "Ficción psicológica",
      pages: 240,
      publisher: "The Russian Messenger",
      language: "Ruso",
      isbn: "9780486434322",
      tags: ["psicología", "adicción", "clásico"],
      description:
        "Un joven tutor lucha contra su obsesión por el juego y sus pasiones personales.",
      price: 18,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLMMDTDnekcsD7yZ-oQvd4LnFMJQSMOtQa0A&s"
    },

    {
      id: 59,
      title: "El mapa del cielo",
      author: "Félix J. Palma",
      category: ["Ciencia ficción", "Aventura", "Fantasía"],
      year: 2012,
      genre: "Fantasía científica",
      pages: 592,
      publisher: "Plaza & Janés",
      language: "Español",
      isbn: "9788401343040",
      tags: ["ciencia ficción", "aventura", "victoriano"],
      description:
        "Una historia que mezcla ciencia ficción y misterio mientras sus personajes enfrentan sucesos inexplicables que desafían la realidad.",
      price: 24,
      image: "https://www.planetadelibros.com.co/usuaris/libros/fotos/400/original/portada_el-mapa-del-cielo-trilogia-victoriana-2_felix-j-palma_202404161711.jpg",
    },
    {
      id: 60,
      title: "La plaza del diamante",
      author: "Mercè Rodoreda",
      category: ["Drama", "Histórico", "Ficción"],
      year: 1962,
      genre: "Drama histórico",
      pages: 304,
      publisher: "Edicions 62",
      language: "Catalán",
      isbn: "9788429719314",
      tags: ["histórico", "Barcelona", "drama"],
      description:
        "Colometa narra su vida marcada por la Guerra Civil Española y las duras condiciones de la época.",
      price: 20,
      image: "https://imagessl0.casadellibro.com/a/l/s5/30/9788411827430.webp"
    },

    {
      id: 61,
      title: "El idiota",
      author: "Fiódor Dostoyevski",
      category: ["Psicológica", "Clásico", "Ficción"],
      year: 1869,
      genre: "Ficción psicológica",
      pages: 667,
      publisher: "The Russian Messenger",
      language: "Ruso",
      isbn: "9780140447926",
      tags: ["psicología", "moral", "clásico"],
      description:
        "El príncipe Mishkin se enfrenta al choque entre su bondad y la corrupción del mundo moderno.",
      price: 27,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/01/f3/01f3bcb19eaa952a48b7e87698d6b181.jpg"
    },

    {
      id: 62,
      title: "La metamorfosis",
      author: "Franz Kafka",
      category: ["Surrealismo", "Clásico", "Ficción"],
      year: 1915,
      genre: "Surrealismo",
      pages: 102,
      publisher: "Kurt Wolff Verlag",
      language: "Alemán",
      isbn: "9780553213690",
      tags: ["surrealismo", "absurdo", "clásico"],
      description:
        "Gregor Samsa despierta convertido en insecto, enfrentando el rechazo familiar y su propia angustia.",
      price: 12,
      image: "https://www.tornamesa.co/imagenes/9788446/978844605473.GIF"
    },

    {
      id: 63,
      title: "Un mundo feliz",
      author: "Aldous Huxley",
      category: ["Distopía", "Ciencia ficción", "Ficción"],
      year: 1932,
      genre: "Distopía",
      pages: 268,
      publisher: "Chatto & Windus",
      language: "Inglés",
      isbn: "9780060850524",
      tags: ["distopía", "ciencia ficción", "control social"],
      description:
        "Una sociedad futurista aparentemente perfecta donde la estabilidad tiene un oscuro precio.",
      price: 18,
      image: "https://images.cdn1.buscalibre.com/fit-in/520x520/c1/8c/c18cdeb80fa6f9a212a1cc5639e94c6d.jpg"
    },

    {
      id: 64,
      title: "Veinte mil leguas de viaje submarino",
      author: "Julio Verne",
      category: ["Aventura", "Ciencia ficción", "Clásico"],
      year: 1870,
      genre: "Aventura científica",
      pages: 416,
      publisher: "Pierre-Jules Hetzel",
      language: "Francés",
      isbn: "9780486434490",
      tags: ["aventura", "ciencia ficción", "clásico"],
      description:
        "El capitán Nemo guía al Nautilus en un viaje extraordinario bajo los mares del mundo.",
      price: 19,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK5WhAg2tXvz6iN_UvF9GdA1Sk8qEO-Zx5Ug&s"
    },

    {
      id: 65,
      title: "La llamada de lo salvaje",
      author: "Jack London",
      category: ["Aventura", "Naturaleza", "Clásico"],
      year: 1903,
      genre: "Aventura",
      pages: 232,
      publisher: "Macmillan",
      language: "Inglés",
      isbn: "9780486264721",
      tags: ["naturaleza", "supervivencia", "clásico"],
      description:
        "Buck, un perro raptado de su hogar, debe adaptarse a la vida salvaje del norte helado.",
      price: 15,
      image:"https://www.loqueleo.es/uploads/2022/07/9788491223979-la-llamada-de-lo-salvaje.jpg"
    },

    {
      id: 66,
      title: "Los detectives salvajes",
      author: "Roberto Bolaño",
      category: ["Contemporáneo", "Experimental", "Ficción"],
      year: 1998,
      genre: "Experimental narrativo",
      pages: 609,
      publisher: "Anagrama",
      language: "Español",
      isbn: "9788433911461",
      tags: ["literatura latinoamericana", "experimental", "moderno"],
      description:
        "Dos jóvenes poetas desaparecen dejando un rastro de historias que narran quienes los conocieron.",
      price: 27,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/21/c2/21c242a51f3a9fe0c44ce4ea8d30dd58.jpg"
    },

    {
      id: 67,
      title: "La historia interminable",
      author: "Michael Ende",
      category: ["Fantasía", "Aventura", "Juvenil"],
      year: 1979,
      genre: "Fantasía",
      pages: 448,
      publisher: "Thienemann Verlag",
      language: "Alemán",
      isbn: "9780140386331",
      tags: ["fantasía", "aventura", "juvenil"],
      description:
        "Un niño se adentra en un libro mágico que lo convierte en protagonista de un mundo en peligro.",
      price: 22,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/5a/b9/5ab929fcb1c7b7780309752e16ff3911.jpg"
    },

    {
      id: 68,
      title: "El nombre del viento",
      author: "Patrick Rothfuss",
      category: ["Fantasía", "Aventura", "Ficción"],
      year: 2007,
      genre: "Fantasía épica",
      pages: 662,
      publisher: "DAW Books",
      language: "Inglés",
      isbn: "9780756404741",
      tags: ["fantasía", "aventura", "bestseller"],
      description:
        "Kvothe narra la historia de su vida: magia, tragedia y búsqueda del conocimiento.",
      price: 29,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/aa/cc/aacc1e2d359a74f3efb144b8ab8f790f.jpg"
    },

    {
      id: 69,
      title: "El marciano",
      author: "Andy Weir",
      category: ["Ciencia ficción", "Aventura", "Ficción"],
      year: 2011,
      genre: "Ciencia ficción realista",
      pages: 387,
      publisher: "Crown",
      language: "Inglés",
      isbn: "9780804139021",
      tags: ["espacio", "ciencia ficción", "supervivencia"],
      description:
        "Un astronauta queda atrapado en Marte y usa su ingenio para sobrevivir.",
      price: 24,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/0b/03/0b030e9492a3e45ebd24d33d77467e08.jpg"

    },

    {
      id: 70,
      title: "El ciclo de la puerta de la muerte: Alas de dragón",
      author: "Margaret Weis y Tracy Hickman",
      category: ["Fantasía", "Aventura", "Ficción"],
      year: 1990,
      genre: "Fantasía épica",
      pages: 416,
      publisher: "Bantam Spectra",
      language: "Inglés",
      isbn: "9780553283938",
      tags: ["fantasía", "aventura", "sagas"],
      description:
        "A través de mundos separados, un misterioso viajero investiga un conflicto ancestral entre razas.",
      price: 21,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJlN5QEWQN2U_i7Fm9PNCSVq6bh8NZkii7w&s"
    },

    {
      id: 71,
      title: "La catedral del mar",
      author: "Ildefonso Falcones",
      category: ["Histórico", "Drama", "Ficción"],
      year: 2006,
      genre: "Histórico medieval",
      pages: 652,
      publisher: "Grijalbo",
      language: "Español",
      isbn: "9788401337207",
      tags: ["histórico", "Barcelona", "medieval"],
      description:
        "La historia de un siervo en la Barcelona medieval que lucha por su libertad.",
      price: 26,
      image: "https://www.penguinlibros.com/co/5393555/la-catedral-del-mar.jpg"
    },

    {
      id: 72,
      title: "La reina oculta",
      author: "Jorge Molist",
      category: ["Histórico", "Aventura", "Ficción"],
      year: 2003,
      genre: "Histórico",
      pages: 560,
      publisher: "Planeta",
      language: "Español",
      isbn: "9788408077779",
      tags: ["histórico", "aventura", "intriga"],
      description:
        "Una joven noble vive entre conspiraciones y secretos durante las Cruzadas.",
      price: 24,
      image: "https://imagessl9.casadellibro.com/a/l/s5/49/9788427034549.webp"
    },

    {
      id: 73,
      title: "Sapiens: De animales a dioses",
      author: "Yuval Noah Harari",
      category: ["Historia", "Ensayo", "Ciencia"],
      year: 2011,
      genre: "Ensayo histórico",
      pages: 498,
      publisher: "Harvill Secker",
      language: "Inglés",
      isbn: "9780062316097",
      tags: ["historia", "ciencia", "humanidad"],
      description:
        "Un recorrido por la historia de la humanidad desde sus orígenes hasta la modernidad.",
      price: 31,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpBevEC2RI4TzbWiVfR1JMxYXXUaQZx5Ql7g&s"
    },

    {
      id: 74,
      title: "Homo Deus: Breve historia del mañana",
      author: "Yuval Noah Harari",
      category: ["Ensayo", "Tecnología", "Ciencia"],
      year: 2015,
      genre: "Ensayo futurista",
      pages: 450,
      publisher: "Harvill Secker",
      language: "Inglés",
      isbn: "9780062464316",
      tags: ["tecnología", "futuro", "ensayo"],
      description:
        "Un análisis de las tendencias tecnológicas y cómo podrían transformar el futuro humano.",
      price: 32,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/21/7d/217df914d30a75624201e6124aefa51e.jpg"
    },

    {
      id: 75,
      title: "La ciudad y los perros",
      author: "Mario Vargas Llosa",
      category: ["Drama", "Latinoamérica", "Ficción"],
      year: 1963,
      genre: "Drama militar",
      pages: 336,
      publisher: "Seix Barral",
      language: "Español",
      isbn: "9788432216062",
      tags: ["latinoamérica", "militar", "drama"],
      description:
        "La dura vida en un colegio militar peruano revela la violencia y la crudeza de la institución.",
      price: 20,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/04/97/0497843aaba916128e3617a02b9a7583.jpg"
    },

    {
      id: 76,
      title: "Conversación en La Catedral",
      author: "Mario Vargas Llosa",
      category: ["Política", "Drama", "Ficción"],
      year: 1969,
      genre: "Ficción política",
      pages: 601,
      publisher: "Seix Barral",
      language: "Español",
      isbn: "9788420469283",
      tags: ["política", "dictadura", "Perú"],
      description:
        "Un periodista reflexiona sobre la corrupción y el poder en el Perú mientras reconstruye su pasado.",
      price: 26,
      image: "https://image.cdn0.buscalibre.com/5b57a6c21dc8618c328b4568.__RS360x360__.jpg"
    },

    {
      id: 77,
      title: "La broma infinita",
      author: "David Foster Wallace",
      category: ["Contemporáneo", "Experimental", "Ficción"],
      year: 1996,
      genre: "Posmodernismo",
      pages: 1104,
      publisher: "Little, Brown and Company",
      language: "Inglés",
      isbn: "9780316066525",
      tags: ["posmodernismo", "experimental", "culto"],
      description:
        "Una compleja obra satírica que retrata adicciones, entretenimiento y vacío existencial.",
      price: 35,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk_g47webP_yGUios6NpVs5lTvHranV0fI2g&s"
    },

    {
      id: 78,
      title: "Shogun",
      author: "James Clavell",
      category: ["Histórico", "Aventura", "Ficción"],
      year: 1975,
      genre: "Ficción histórica",
      pages: 1152,
      publisher: "Atheneum",
      language: "Inglés",
      isbn: "9780440178002",
      tags: ["samurái", "Japón", "histórico"],
      description:
        "Un navegante europeo naufraga en Japón y se ve envuelto en luchas de poder entre señores feudales.",
      price: 33,
      image: "https://pendulo.com/imagenes_grandes/9798212/979821289519.GIF"
    },

    {
      id: 79,
      title: "Dune",
      author: "Frank Herbert",
      category: ["Ciencia ficción", "Aventura", "Ficción"],
      year: 1965,
      genre: "Ciencia ficción épica",
      pages: 896,
      publisher: "Chilton Books",
      language: "Inglés",
      isbn: "9780441172719",
      tags: ["ciencia ficción", "épica", "aventura"],
      description:
        "Paul Atreides enfrenta conflictos políticos, ecológicos y espirituales en un planeta desértico.",
      price: 30,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIwCFQnOP_q5wg-hkd9ssYUQShVBWD_BRigA&s"
    },

    {
      id: 80,
      title: "Fundación",
      author: "Isaac Asimov",
      category: ["Ciencia ficción", "Clásico", "Ficción"],
      year: 1951,
      genre: "Ciencia ficción",
      pages: 255,
      publisher: "Gnome Press",
      language: "Inglés",
      isbn: "9780553293357",
      tags: ["ciencia ficción", "clásico", "imperio"],
      description:
        "La caída de un imperio galáctico impulsa un plan matemático para preservar el conocimiento humano.",
      price: 20,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3_C_0n51R5KBPkfvpiiYefzZIQ3SjAQsqww&s"
    },

    {
      id: 81,
      title: "La canción de Aquiles",
      author: "Madeline Miller",
      category: ["Mitología", "Romance", "Ficción"],
      year: 2011,
      genre: "Mitología griega moderna",
      pages: 417,
      publisher: "Ecco Press",
      language: "Inglés",
      isbn: "9780062060617",
      tags: ["mitología", "Troya", "épico"],
      description:
        "La historia de Aquiles y Patroclo reimaginada desde una perspectiva íntima y emocional.",
      price: 22,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/62/2a/622a5056bcae6768c6461ea5d156b25c.jpg"
    },

    {
      id: 82,
      title: "Circe",
      author: "Madeline Miller",
      category: ["Mitología", "Fantasía", "Ficción"],
      year: 2018,
      genre: "Reimaginación mitológica",
      pages: 400,
      publisher: "Little, Brown and Company",
      language: "Inglés",
      isbn: "9780316556347",
      tags: ["mitología", "diosas", "ficción"],
      description:
        "La vida de Circe, hija del dios Helios, en un relato que mezcla magia, tragedia y libertad.",
      price: 24,
      image: "https://images.cdn1.buscalibre.com/fit-in/360x360/50/ec/50ec806b0997aa1b2cd6e9bd81250776.jpg"
    },

    {
      id: 83,
      title: "La invención de Morel",
      author: "Adolfo Bioy Casares",
      category: ["Ciencia ficción", "Latinoamérica", "Ficción"],
      year: 1940,
      genre: "Ficción fantástica",
      pages: 152,
      publisher: "Losada",
      language: "Español",
      isbn: "9788420662400",
      tags: ["fantástico", "latinoamérica", "misterio"],
      description:
        "Un fugitivo llega a una isla donde nada es lo que parece gracias a una misteriosa máquina.",
      price: 18,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/d6/1e/d61e1e190321819e8e63150d4e62a639.jpg"
    },

    {
      id: 84,
      title: "Solaris",
      author: "Stanisław Lem",
      category: ["Ciencia ficción", "Filosofía", "Ficción"],
      year: 1961,
      genre: "Filosofía científica",
      pages: 204,
      publisher: "Czytelnik",
      language: "Polaco",
      isbn: "9780156027601",
      tags: ["ciencia ficción", "psicología", "filosofía"],
      description:
        "Un psicólogo estudia un planeta viviente que confronta a los humanos con sus recuerdos más profundos.",
      price: 21,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/b9/6a/b96a341f774d5c7b56b1f74863fa41c3.jpg"
    },

    {
      id: 85,
      title: "Kafka en la orilla",
      author: "Haruki Murakami",
      category: ["Surrealismo", "Contemporáneo", "Ficción"],
      year: 2002,
      genre: "Surrealismo moderno",
      pages: 505,
      publisher: "Shinchosha",
      language: "Japonés",
      isbn: "9781400079278",
      tags: ["surrealismo", "misterio", "contemporáneo"],
      description:
        "Dos historias paralelas se entrelazan en un viaje simbólico lleno de enigmas y metáforas.",
      price: 26,
      image: "https://images.cdn2.buscalibre.com/fit-in/360x360/ae/fa/aefadf196fc977aaaf382e37d17c3970.jpg"
    },

    {
      id: 86,
      title: "Árbol de humo",
      author: "Denis Johnson",
      category: ["Guerra", "Drama", "Ficción"],
      year: 2007,
      genre: "Drama bélico",
      pages: 624,
      publisher: "Farrar, Straus and Giroux",
      language: "Inglés",
      isbn: "9780375700927",
      tags: ["guerra", "Vietnam", "drama"],
      description:
        "Una historia intensa que muestra las sombras morales y psicológicas de la Guerra de Vietnam.",
      price: 28,
      image: "https://image.cdn1.buscalibre.com/60e395758463b5f3158bc3b6.RS500x500.jpg"
    },

    {
      id: 87,
      title: "La amiga estupenda",
      author: "Elena Ferrante",
      category: ["Drama", "Contemporáneo", "Ficción"],
      year: 2011,
      genre: "Ficción contemporánea",
      pages: 336,
      publisher: "Edizioni E/O",
      language: "Italiano",
      isbn: "9781609450786",
      tags: ["amistad", "Italia", "contemporáneo"],
      description:
        "La historia de dos amigas cuya relación evoluciona en la Italia pobre de la posguerra.",
      price: 21,
      image: "https://www.tornamesa.co/imagenes/9788426/978842642459.GIF"
    },

    {
      id: 88,
      title: "American Gods",
      author: "Neil Gaiman",
      category: ["Fantasía", "Mitología", "Ficción"],
      year: 2001,
      genre: "Fantasía moderna",
      pages: 465,
      publisher: "William Morrow",
      language: "Inglés",
      isbn: "9780380789030",
      tags: ["fantasía", "mitología", "contemporáneo"],
      description:
        "Un exconvicto se ve envuelto en una guerra entre dioses antiguos y modernos en Estados Unidos.",
      price: 23,
      image: "https://images.cdn3.buscalibre.com/fit-in/360x360/1b/21/1b215e945d4f23fb56a2b0cd039c81d2.jpg"
    },

    {
      id: 89,
      title: "El mapa del tiempo",
      author: "Félix J. Palma",
      category: ["Ciencia ficción", "Aventura", "Ficción"],
      year: 2008,
      genre: "Fantasía victoriana",
      pages: 608,
      publisher: "Plaza & Janés",
      language: "Español",
      isbn: "9788401337276",
      tags: ["viajes en el tiempo", "victoriano", "aventura"],
      description:
        "Una novela que mezcla viajes temporales, Londres victoriano y las ideas de H. G. Wells.",
      price: 25,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-qgp8L6fh4vvC7ilp4k1s2yfLafNXbQgR6A&s"
    },

    {
      id: 90,
      title: "La biblioteca de los muertos",
      author: "Glenn Cooper",
      category: ["Thriller", "Misterio", "Ficción"],
      year: 2009,
      genre: "Thriller histórico",
      pages: 432,
      publisher: "Arrow Books",
      language: "Inglés",
      isbn: "9780099545756",
      tags: ["thriller", "misterio", "histórico"],
      description:
        "Un arqueólogo descubre una biblioteca que contiene las fechas de muerte de todas las personas del mundo.",
      price: 23,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLBob55H7V4giCMFQutkpqinlkP-jqdzw7EA&s"
    },
  ];
};

export const booksMap: Map<string, IBooks> = new Map(
  myBackend().map((book) => [book.isbn, book])
);



